---
title: "The macroeconomic burden of noncommunicable diseases and mental health conditions in South America."
author: 
    - Maddalena Ferranna
    - Daniel Cadarette
    - Simiao Chen
    - Parastou Ghazi
    - Faith Ross
    - Leo Zucker
    - David E. Bloom
date: "7/11/2023"
---

In [_PLOS One_](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0293144)

Noncommunicable diseases and mental health conditions (referred to collectively as NMHs) are the greatest cause of preventable death, illness, and disability in South America and negatively affect countries’ economic performance through their detrimental impacts on labor supply and capital investments. Sound, evidence-based policy-making requires a deep understanding of the macroeconomic costs of NMHs and of their distribution across countries and diseases. The paper estimates and projects the macroeconomic burden of NMHs over the period 2020–2050 in 10 South American countries. We estimate the impact of NMHs on gross domestic product (GDP) through a human capital-augmented production function approach, accounting for mortality and morbidity effects of NMHs on labor supply, for the impact of treatment costs on physical capital accumulation, and for variations in human capital by age. Our central estimates suggest that the overall burden of NMHs in these countries amounts to $7.3 trillion (2022 international $, 3% discount rate, 95% confidence interval: $6.8–$7.8 trillion). Overall, the macroeconomic burden of NMHs is around 4% of total GDP over 2020–2050, with little variation across countries (from 3.2% in Peru to 4.5% in Brazil). In other words, without NMHs, annual GDP over 2020–2050 would be about 4% larger. In most countries, the largest macroeconomic burden is associated with cancers. Results from the paper point to a significant macroeconomic burden of NMHs in South America and provide a strong justification for investment in NMH prevention, early detection, treatment, and formal and informal care.